import { pgTable, text, uuid, timestamp, jsonb, boolean, integer, numeric, index } from 'drizzle-orm/pg-core'
import type { ShipmentInput, CustomsInput } from '../src/lib/shipping.js'

export const services = pgTable('shipping_services', { id: uuid('id').primaryKey().defaultRandom(), name: text('name').notNull(), description: text('description').notNull().default(''), minDays: integer('min_days').notNull(), maxDays: integer('max_days').notNull(), enabled: boolean('enabled').notNull().default(false), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const rates = pgTable('shipping_rates', { id: uuid('id').primaryKey().defaultRandom(), serviceId: uuid('service_id').notNull().references(() => services.id), originCity: text('origin_city').notNull(), destinationCountry: text('destination_country').notNull(), currency: text('currency').notNull(), base: numeric('base', { precision: 16, scale: 2 }).notNull(), perKg: numeric('per_kg', { precision: 16, scale: 2 }).notNull(), perPackage: numeric('per_package', { precision: 16, scale: 2 }).notNull(), volumetricDivisor: numeric('volumetric_divisor').notNull(), enabled: boolean('enabled').notNull().default(true), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() })
export const shipments = pgTable('shipments', {
  id: uuid('id').primaryKey().defaultRandom(), trackingNumber: text('tracking_number').notNull().unique(), ownerId: uuid('owner_id').notNull(), originCountry: text('origin_country').notNull().default('RU'), originCity: text('origin_city').notNull(), destinationCountry: text('destination_country').notNull(), destinationCity: text('destination_city').notNull(), serviceId: uuid('service_id').notNull().references(() => services.id), details: jsonb('details').$type<ShipmentInput>().notNull(), status: text('status').notNull().default('Shipment Created'), currentLocation: text('current_location').notNull(), estimatedDelivery: text('estimated_delivery'), customs: jsonb('customs').$type<CustomsInput>().notNull().default({ status: 'Not submitted', declarationStatus: 'Not submitted', reference: '', goodsDescription: '', hold: false, release: false, notes: '' }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, table => [index('shipments_owner_idx').on(table.ownerId), index('shipments_destination_idx').on(table.destinationCountry), index('shipments_status_idx').on(table.status)])
export const events = pgTable('tracking_events', { id: uuid('id').primaryKey().defaultRandom(), shipmentId: uuid('shipment_id').notNull().references(() => shipments.id), country: text('country').notNull(), city: text('city').notNull(), facility: text('facility').notNull().default(''), status: text('status').notNull(), description: text('description').notNull(), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), actorId: uuid('actor_id').notNull() }, table => [index('events_shipment_idx').on(table.shipmentId)])
export const notes = pgTable('internal_notes', { id: uuid('id').primaryKey().defaultRandom(), shipmentId: uuid('shipment_id').notNull().references(() => shipments.id), actorId: uuid('actor_id').notNull(), text: text('text').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })
export const audit = pgTable('audit_log', { id: uuid('id').primaryKey().defaultRandom(), actorId: uuid('actor_id').notNull(), action: text('action').notNull(), entityId: uuid('entity_id').notNull(), changes: jsonb('changes').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })
export const quotes = pgTable('shipping_quotes', { id: uuid('id').primaryKey().defaultRandom(), ownerId: uuid('owner_id').notNull(), rateId: uuid('rate_id').notNull().references(() => rates.id), inputs: jsonb('inputs').notNull(), amount: numeric('amount', { precision: 16, scale: 2 }).notNull(), currency: text('currency').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull() })
